version: "3"
services:
  frontend:
    build:
      context: ./Frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend


  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    env_file:
      - ./Backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
  frontend-dist:
